---
- name: Ensure that APT works with the https method
  apt: name={{ item }} state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common

- name: Install GPG key
  shell: curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  tags:
    - kubernetes
    - gpg_key

- name: Add  apt repository
#  apt_repository: repo="deb http://apt.kubernetes.io/{{ ansible_distribution|lower }}-{{ ansible_distribution_release }} main" state=present
  apt_repository: repo="deb http://apt.kubernetes.io/ kubernetes-xenial main" state=present
  tags:
    - kubernetes
    - apt_repository

- name: Update apt-cache
  apt: update_cache=yes
  tags:
    - kubernetes
    - apt_cache

- name: Install kubernetes package
  apt: name={{ item }}  state=present
  notify: Install Kubernetes
  with_items:
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni
  tags:
    - kubernetes
    - install
